name: CI

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      
      - id: first_environment
        run: |
          # jq '[ .[] | startswith("environment-") ]' < 
          echo -e "${{ toJson(github.event.issue.labels) }}"
          ENVIRONMENT_NAME="staging"
          CURRENT_ENVIRONMENT_INDEX=$(jq '[ .environments[] | . == "'"$ENVIRONMENT_NAME"'"] | index(true)' environments.json)
          ENVIRONMENT_LENGTH=$(jq -r '.environments | length' environments.json)
          NEXT_ENVIRONMENT=$(jq -r '.environments['"$((CURRENT_ENVIRONMENT_INDEX + 1))"']' environments.json)

          echo "Current environment name $ENVIRONMENT_NAME"
          echo "Next environment name $NEXT_ENVIRONMENT"
          echo "Current environment index $CURRENT_ENVIRONMENT_INDEX"
          echo "Environment length $ENVIRONMENT_LENGTH"
          
          if [ $NEXT_ENVIRONMENT = "null" ]
          then
            echo "No next environment"
            exit 1
          fi
          
          #  echo "::set-output name=first-environment::$( echo "$FIRSTENVIRONMENT" )"
          
      # Runs a set of commands using the runners shell
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
