name: CI

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      
      - id: first_environment
        run: |
          ISSUE_TITLE=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
          VERSION="${ISSUE_TITLE/\[Release\] /}"
          echo "Version is $VERSION"
          
          
          CURRENT_ENVIRONMENT_INDEX=-1
          while read i; do
            ENVIRONMENT_NAME="${i/environment-/}"
            echo "Checking $ENVIRONMENT_NAME"
            ENVIRONMENT_INDEX=$(jq '[ .environments[] | . == "'"$ENVIRONMENT_NAME"'"] | index(true)' environments.json)
            echo "Environment index $ENVIRONMENT_INDEX"
            
            if (( ENVIRONMENT_INDEX > CURRENT_ENVIRONMENT_INDEX )); then
              echo "Updating environment index to $ENVIRONMENT_INDEX"
              CURRENT_ENVIRONMENT_INDEX=$ENVIRONMENT_INDEX
            else
              echo "Not updating environment index to $ENVIRONMENT_INDEX"
            fi
          done < <(jq -r '[ .issue.labels[] | select(.name | startswith("environment-")) | .name ] | .[]' $GITHUB_EVENT_PATH)                
                   
          ENVIRONMENT_LENGTH=$(jq -r '.environments | length' environments.json)
          NEXT_ENVIRONMENT=$(jq -r '.environments['"$((CURRENT_ENVIRONMENT_INDEX + 1))"']' environments.json)

          echo "Current environment name $ENVIRONMENT_NAME"
          echo "Next environment name $NEXT_ENVIRONMENT"
          echo "Current environment index $CURRENT_ENVIRONMENT_INDEX"
          echo "Environment length $ENVIRONMENT_LENGTH"
          
          if [ $NEXT_ENVIRONMENT = "null" ]
          then
            echo "No next environment"
            exit 1
          fi
          
          #  echo "::set-output name=first-environment::$( echo "$FIRSTENVIRONMENT" )"
          
      # Runs a set of commands using the runners shell
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
